
title: Camera Crop Factor
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


# ----------------------------------------
# Include/Exclude
include: ['assets/_images/ui']
exclude: ['node_modules', 'Gulpfile.js', 'package.json', 'README.md', '*.sublime-*', '.publish', '.git', 'feed.xml', 'feed.xslt.xml', 'assets/sass']
keep_files: ['assets/css', 'assets/js']


# ----------------------------------------
# Directory structures
# change to source and dist for easier deploy
source      : _src
destination : _dev
